#!/bin/bash

SERVICE=node # Corresponds to docker-compose.yml:2

if [ $# -eq 0 ]; then
  echo -e "\n 💡 Pass \`bash\` as first arg to enter shell\n"
  docker compose up
elif [ "$1" = "stop" ]; then
  docker compose down
elif [ "$1" = "logs" ]; then
  docker compose logs -f
elif [ "$(docker compose ps -q $SERVICE)" ]; then
  # If the container is running, use exec
  docker compose exec $SERVICE "$@"
else
  # If the container is not running, use run
  docker compose run --service-ports --rm --build --remove-orphans $SERVICE "$@"
fi
