services:
  node:
    container_name: node
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app # host:container
      - pnpm:/pnpm/store
    ports:
      - "5173:5173" # host:container
    environment:
      - NODE_ENV=development
    # env_file:
    #   - .env
    command: >
      bash -c "pnpm i && pnpm dev:docker"

volumes:
  pnpm:
